### ISSUE TITLE
Make ioctl usable for more than just TIOCGWINSZ

### ISSUE THREAD

**Issue by posborne** [carllerche/nix-rust#108]
The version of ioctl that is currently present in nix is not particularly useful (only has support for TIOCGWINSZ) and the design would require that the library itself be modified in order to add additional ioctls.  I would like to see nix support a good lower-level ioctl implementation that can be used to raise the level of abstraction for any rust code that needs to send ioctls to regular and special files.

My immediate need for something like this is in implementing a library that provides access to Linux spidev devices (https://www.kernel.org/doc/Documentation/spi/spidev / http://lxr.free-electrons.com/source/include/uapi/linux/spi/spidev.h), but there are many, many devices out there that require ioctl for normal operation.  I think there is probably some interface that can be provided that provides a little more help to implementers than what is currently available (and more than the libc ioctl).

A good starting place seems to be looking at the low-level macros available in the ioctl header: http://lxr.free-electrons.com/source/include/uapi/asm-generic/ioctl.h

I am going to play with things and see if I can come up with a more concrete proposal for a refined design for ioctls.

**Comment by posborne** [comment]
I have an initial version of an ioctl module available here: https://github.com/posborne/rust-spidev/blob/master/src/ioctl.rs

I am going to play with that implementation a bit more and will then probably open a PR that get the module pulled into nix.  If there is any early feedback based on the linked implementation, please let me know and I will see if I can address before I issue an initial PR.

**Comment by carllerche** [comment]
Hey there. I personally don't have much experience w/ working with ioctl. I would be happy to pull in a more comprehensive binding. I believe @utkarshkukreti did the original work, so hopefully he will have more of an opinion :)

**Comment by carllerche** [comment]
@posborned any luck with this?

**Comment by posborne** [comment]
@carllerche, things are progressing.  I will submit a PR once I have had a chance to test a little bit more.  That testing will be done with the spidev development I have been doing (since that requires a number of ioctls).  I have hardware for testing that now, so expect to see a PR sometime this week.
