### ISSUE TITLE
`impl AsExtStr for OsStr` does not convert to a proper C string

### ISSUE THREAD

**Issue by dead10ck** [carllerche/nix-rust#117]
I started noticing some strange behavior when trying to use the `lstat` function I recently submitted; `lstat` seemed to be returning `ENOENT` when the file did indeed exist, and opened correctly with `File::open()`. I began investigating, and I think I've found the cause: the implementation of `AsExtStr` for `OsStr`:

```rust
/// Converts a value to an external (FFI) string representation
trait AsExtStr {
    fn as_ext_str(&self) -> *const libc::c_char;
}

impl AsExtStr for OsStr {
    fn as_ext_str(&self) -> *const libc::c_char {
        self.as_bytes().as_ptr() as *const libc::c_char
    }
}
```

It appears the problem is that this just borrows the byte slice from the `OsStr` and then simply casts to a `libc::c_char`. If I am not mistaken, believe that this does not properly convert to a null-terminated C string. I was able to construct a rather interesting test case which showcases this (you can paste this at the bottom of `src/lib.rs` to test for yourself):

```rust
#[cfg(test)] use libc::funcs::c95::stdio;
#[cfg(test)] use std::ffi::CStr;
#[test]
#[allow(unused_variables)]
fn test_as_ext_str() {
    let foo_str = "foo";
    let bar_str = "bar";
    let s = Path::new(foo_str).as_os_str();
    let ext_str = s.as_ext_str();
    unsafe { stdio::puts(ext_str); }
    let cstr = unsafe { CStr::from_ptr(ext_str) };
    let back_to_str = std::str::from_utf8(cstr.to_bytes()).unwrap();
    assert_eq!(foo_str, back_to_str);
}
```

This is the output:

```sh
dead10ck at arch-laptop in ~/src/rust/nix-rust (master●)
$ cargo test test_as_ext_str
     Running target/debug/nix-21d2363c10db6dc6

running 1 test
foobarsrc/lib.rs
test test_as_ext_str ... FAILED

failures:

---- test_as_ext_str stdout ----
	thread 'test_as_ext_str' panicked at 'assertion failed: `(left == right)` (left: `"foo"`, right: `"foobarsrc/lib.rs"`)', src/lib.rs:167



failures:
    test_as_ext_str

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured

thread '<main>' panicked at 'Some tests failed', /home/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libtest/lib.rs:259

```

You can see just below the `running 1 test` line the output of the call to `libc`'s `puts` function. The input string was "foo", but because the pointer that `as_ext_str` returned was not properly null-terminated, it also printed out some other strings that were adjacent in memory.

This will likely be non-trivial to fix, since `AsExtStr` is used in many places throughout the crate; a proper `CStr` or `CString` will probably need to be constructed from the `OsStr` argument, and that should be returned instead of a raw pointer. What do you think?

**Comment by carllerche** [comment]
Thanks for this report. Sorry for the delay. I'm going to deal w/ this now. I'm surprised by this behavior and I guess I misunderstood the guarantees around `OsStr`. I'm going to try to do a bit of investigation first though...

**Comment by carllerche** [comment]
ok, tl;dr I was wrong.
