### ISSUE TITLE
unistd::pivot_root() is possibly broken

### ISSUE THREAD

**Issue by dead10ck** [carllerche/nix-rust#120]
While implementing a fix for #117, I noticed that `unistd::pivot_root()` is possibly broken.

On 9 Feb, effb423 introduced the `NixPath` trait, which at first took a closure which has a `*const libc::c_char` as an argument, and `unistd::pivot_root()` was changed to use `with_nix_path()` and its closure's arguments as arguments in the call to `sys::syscall::syscall()`.

Then on 26 Feb, e8a58c8 changed `NixPath` to take an `&OsStr` instead of a `*const libc::c_char`, but `unistd::pivot_root()` was not updated. So it appears that `unistd::pivot_root()` is now passing `&OsStr`s to `sys::syscall::syscall()`. I imagine this wasn't caught because `unistd::pivot_root()` doesn't appear to be covered by any unit tests.

**Comment by carllerche** [comment]
Resolved by: 21fb1394a111d19079da90a4d31171b0d6adc27c
