### ISSUE TITLE
Open to adding gettid?

### ISSUE THREAD

**Issue by moehts** [carllerche/nix-rust#129]
Seeing that pthreads is out of nix's scope, could you add linux's `gettid` system call so that individual threads can be interacted with. At present, system calls can only operate on entire processes as a whole. 

Implementing it strait forward since the system call, like getpid, takes no argument. (imo, It's even easier if you're willing to add the syscall crate as a dependency to abstract away architectural differences, but the crate uses `no_std`).

Side note: Thank you for this crate! I was in the middle of re-implementing it before it caught my eye. Very well made.

**Comment by carllerche** [comment]
Sure!

**Comment by carllerche** [comment]
I would take a PR for this. Going to close the issue for now.
