### ISSUE TITLE
ARM fix

### ISSUE THREAD

**Issue by SirVer** [carllerche/nix-rust#131]
I recently compiled nix for my beagleboard black - it went smoothly, but I got two compile errors, both in uio.rs.

The parameter `offset` to ffi::pread and ffi::pwrite are i32 on my arm. Maybe they should be isize? I am not sure how to express that in rust in a portable manner.

**Comment by posborne** [comment]
I think using `off_t` here is the right thing to do but `off_t` does not have the right value for ARM in your environment.  Reading the libc lib.rs, it would appear that `off_t` should be an `i32`: https://github.com/rust-lang/rust/blob/8b7c17db2235a2a3f2c71242b11fc429a8d05a90/src/liblibc/lib.rs#L454

**Comment by SirVer** [comment]
I am sorry, my original bug description was not super great. I was back at my machine today and conjectured a fix real quick in attached pull request.

**Comment by carllerche** [comment]
Fixed by d9808975608e7818be2d564357469dab0a31e1d2

**Comment by SirVer** [comment]
thanks!
