### ISSUE TITLE
Additional Signal codes

### ISSUE THREAD

**Issue by danReynolds** [carllerche/nix-rust#139]
Is there a reason why there aren't some signals like SIGSTP? I want to handle ctrl+z as well. Is there a standard that we are completing or have these ones just been specifically chosen at https://carllerche.github.io/nix-rust/nix/sys/signal/index.html ? Thanks guys.

**Comment by carllerche** [comment]
Sorry for the delay (on vacation). There is no real reason. Signal support is still a work in progress...

cc @geofft the resident signal expert :smile:
