### ISSUE TITLE
Illegal hardware instruction on Mac OS when using signals

### ISSUE THREAD

**Issue by nikklassen** [carllerche/nix-rust#140]
Hi.  I have the following program
```rust
extern crate nix;
extern crate libc;

use std::thread;
use nix::sys::signal;

extern "C" fn handle_signal(val: libc::c_int) {
    println!("Handling");
}

fn main() {
    let sig_action = signal::SigAction::new(
        handle_signal,
        signal::SockFlag::empty(),
        signal::SigSet::empty()
        );
    unsafe { let _ = signal::sigaction(signal::SIGINT, &sig_action).unwrap(); }
    loop {
        thread::sleep_ms(100);
    }
}
```

When I run this program and hit ^C I get the output "Illegal instruction: 4" and the program crashes

My system information is
libc: v0.1.8
nix: v0.3.7
Mac OS: 10.10.3
rustc --version:  1.2.0-nightly (9ad0063a1 2015-06-20)

I believe this has to do with the implementation of [sigaction](https://github.com/carllerche/nix-rust/blob/master/src/sys/signal.rs#L267).  When I reimplement this struct myself like so the sigaction function call works
```rust
#[repr(C)]
pub struct sigaction {
    pub sa_handler: extern fn(libc::c_int),
    pub sa_sigaction: extern fn(libc::c_int, *mut siginfo_t, *mut libc::c_void),
    pub sa_mask: sigset_t,
    pub sa_flags: libc::c_int,
    pub sa_restorer: extern fn(),
}

type sigaction_t = self::sigaction;
```
Thanks in advance

**Comment by carllerche** [comment]
Sorry for the delay (on vacation). You are most likely correct that there is an issue w/ the sigaction binding. I would greatly appreciate a PR :smile: 

cc @geofft

**Comment by nikklassen** [comment]
No worries.  I can definitely make a PR for you.

**Comment by geofft** [comment]
Yeah, nix should probably resync with [libstd/sys/unix/c.rs](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/c.rs) at some point; I think that's where many of those bindings came from.

I don't _think_ your prototype is correct (`sa_handler` and `sa_sigaction` overlap, and there's no `sa_restorer` on OS X), so I'm a little confused about why one crashes and not the other. It's possible I'm looking at the wrong struct definition, but I believe the one to use is the bare `struct sigaction` in [xnu's bsd/sys/signal.h](http://www.opensource.apple.com/source/xnu/xnu-2782.1.97/bsd/sys/signal.h) (as opposed to `struct __sigaction`, which is what nix looks to be currently binding). Perhaps there's something subtle happening with uninitialized values.
