### ISSUE TITLE
statvfs and fstatvfs support

### ISSUE THREAD

**Issue by hyunsik** [carllerche/nix-rust#146]
There is no way to get file system statistic information in Rust. It would be great if nix-rust supports these system calls.

**Comment by carllerche** [comment]
:+1: I would happilly accept a PR for this!

**Comment by hyunsik** [comment]
Sounds good to me. I'll try it.

**Comment by vertexclique** [comment]
:+1: for that! @hyunsik

**Comment by carllerche** [comment]
@hyunsik any luck?

**Comment by polachok** [comment]
I'm working on this one

**Comment by carllerche** [comment]
Looking forward to it!

**Comment by hyunsik** [comment]
I'm sorry for late response. Also, thank you @polachok for your contribution.

**Comment by vertexclique** [comment]
:+1: thanks for all the fish :)
