### ISSUE TITLE
Intermittent failure in test_unistd::test_wait

### ISSUE THREAD

**Issue by joekain** [carllerche/nix-rust#155]
I see occasional failures in test_unistd::test_wait if I run cargo test over and over:

    failures:

    ---- test_unistd::test_wait stdout ----
    	thread 'test_unistd::test_wait' panicked at 'assertion failed: `(left == right)` (left: `Ok(Exited(14028))`, right: `Ok(Exited(14031))`)', test/test_unistd.rs:41

    ---- test_unistd::test_execve stdout ----
    	thread 'test_unistd::test_execve' panicked at 'called `Result::unwrap()` on an `Err` value: Sys(ECHILD)', /home/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:729

    failures:
        test_unistd::test_execve
        test_unistd::test_wait

    test result: FAILED. 21 passed; 2 failed; 0 ignored; 0 measured

**Comment by joekain** [comment]
The problem is that `cargo test` runs the tests in parallel and the test may span multiple child processes at once.  Then calling `wait` will return when any of the child processes stop.  `test_wait` only expects wait to return for its child.

@cmr suggested using RUST_TEST_THREADS=1 as a work around.

**Comment by carllerche** [comment]
I'm OK w/ that. It would be nice for there to be a way to default to this in Cargo.toml

**Comment by carllerche** [comment]
Merged this: https://github.com/carllerche/nix-rust/commit/06aaa83e5da19dd35908ba42de6f7ed12a66553f
