### ISSUE TITLE
compile failure against latest version of libc

### ISSUE THREAD

**Issue by danburkert** [carllerche/nix-rust#159]
libc 0.1.9 was just released, and nix on linux is failing to compile against it:

```bash
Compiling nix v0.3.9 (file:///vagrant/nix-rust)
src/sys/ioctl.rs:204:38: 204:57 error: mismatched types:
 expected `u64`,
    found `i32`
(expected u64,
    found i32) [E0308]
src/sys/ioctl.rs:204     convert_ioctl_res(libc_ioctl(fd, op as os_ioctl_op_t, data_ptr))
                                                          ^~~~~~~~~~~~~~~~~~~
src/sys/ioctl.rs:204:38: 204:57 help: run `rustc --explain E0308` to see a detailed explanation
src/sys/ioctl.rs:216:38: 216:57 error: mismatched types:
 expected `u64`,
    found `i32`
(expected u64,
    found i32) [E0308]
src/sys/ioctl.rs:216     convert_ioctl_res(libc_ioctl(fd, op as os_ioctl_op_t, data as *const T))
                                                          ^~~~~~~~~~~~~~~~~~~
src/sys/ioctl.rs:216:38: 216:57 help: run `rustc --explain E0308` to see a detailed explanation
src/sys/ioctl.rs:223:47: 223:66 error: mismatched types:
 expected `u64`,
    found `i32`
(expected u64,
    found i32) [E0308]
src/sys/ioctl.rs:223     convert_ioctl_res(unsafe { libc_ioctl(fd, op as os_ioctl_op_t) })
                                                                   ^~~~~~~~~~~~~~~~~~~
src/sys/ioctl.rs:223:47: 223:66 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to 3 previous errors
Could not compile `nix`.
```

**Comment by yupeng820921** [comment]
Thanks danburkert, I just hit the exactly same error, and set the nix to danburkert's repo in Cargo.toml can solve this issue:
[dependencies]
nix = { git = "https://github.com/danburkert/nix-rust" }

**Comment by rorytrent** [comment]
@yupeng820921 , I was able to compile nix using this fix, but when it is listed as a sub-dependency in one of the other included libraries it still attempts to compile the broken version. Do you know of any fix for that besides forking the other dependency or waiting for this repo to be updated?

**Comment by danburkert** [comment]
@rorytrent the mechanism that would allow you to do this in Cargo appears to be broken: https://github.com/rust-lang/cargo/issues/1800.  A quick and dirty fix is to manually edit your local Cargo.lock file and replace any instances of the libc 0.1.9 dependency with 0.1.8.

**Comment by carllerche** [comment]
Looks like libc 0.1.9 was yanked. I'm going to close this issue.
