### ISSUE TITLE
sys::epoll::EpollEvent needs #[derive(Clone, Copy)] for Android as well

### ISSUE THREAD

**Issue by overminder** [carllerche/nix-rust#165]
Hi,

I failed to cross-compile `nix 0.3.9` for `arm-linux-androideabi` on a `rustc 1.1.0-dev`. The error message was ``error: the trait `core::clone::Clone` is not implemented for the type `sys::epoll::EpollEvent` [E0277]``.

Looking at [src/sys/epoll.rs](https://github.com/carllerche/nix-rust/blame/a384b1d7be2d634c4a564e70c77af3a466782f75/src/sys/epoll.rs#L97) it seems that `EpollEvent` is missing a `derive(Clone)` for `cfg(all(target_os = "android", not(target_arch = "x86_64")))`.

**Comment by carllerche** [comment]
Thanks for the report!
