### ISSUE TITLE
Doesn't support abstract UNIX sockets

### ISSUE THREAD

**Issue by stouset** [carllerche/nix-rust#169]
To use a socket in the abstract namespace, one `bind()`s a socket to a path beginning with a NUL byte. Unfortunately, there's an [explicit test](https://github.com/carllerche/nix-rust/blob/master/src/lib.rs#L99) that fails on a NUL encountered in a path. Additionally, functions like `strcpy()` [are called](https://hoverbear.github.io/raft/src/nix/sys/socket/addr.rs.html#351) in parts of the library, and won't work if there's a NUL that's not the last byte in the string.

**Comment by stouset** [comment]
I discovered one other related issue prohibiting this kind of use.

When `bind()` is called, a length is passed. This length specifies the size of the `sockaddr` struct passed. In the case where `sun_path` is a filesystem path, it's fine to pass `sizeof(sockaddr_un)` since the path is terminated with a NUL byte. In the abstract namespace case, the length passed must be the size of actual path intended (plus the two bytes for `sun_family`) — NULs have no special meaning and are ignored.

**Comment by carllerche** [comment]
Hmmm... thanks for the report. I am going to have to read up on abstract UDS.

**Comment by stouset** [comment]
They're (conceptually) pretty simple. If you provide a path that's prefixed with a "\0", the address provided won't refer to a location on the filesystem. Additionally, the path will not be treated as a NUL-terminated string. This last bit is the only semi tricky bit to implement in `nix` — you will need to remember somewhere the length of the path given, since something like `\0foo\0\0` with length 4 could be a perfectly valid abstract path which would be distinct from `\0foo\0\0\0` with length 5.

**Comment by carllerche** [comment]
I think the way to fix this would be to take an Option path to represent the abstract socket. I would take a PR for this. It would be a breaking change so the nix version would need to be bumped.

**Comment by stouset** [comment]
Happy to provide. I'm getting back up to speed w/ Rust after several months away, so apologies if I'm a bit slow. I assume you mean an `Option<NixPath>` to `UnixAddr::new()`? I'm not sure how this distinguishes between an abstract path and a filesystem path.

**Comment by carllerche** [comment]
Ok, I took a look.

[`SocketAddr`](https://github.com/carllerche/nix-rust/blob/master/src/sys/socket/addr.rs#L403-L406) is an `Inet` or `Unix` addr. `UnixAddr` contains a libc::sockaddr_un, which would have a null path to indicate an abstract socket.

I would think that the best way to handle this would be to add `UnixAddr::abstract()` that returns an abstract unix address. However, existing addr related code would need to be audited to ensure that the abstract socket case is handled internally.

**Comment by stouset** [comment]
A `NULL` `sun_path` doesn't indicate an abstract socket. A `sun_path` *starting* with a `NULL` byte does. Unfortunately, this means we also have to store the length of the path provided, as abstract paths are not `NULL`-terminated strings (whereas filesystem paths are).

**Comment by geofft** [comment]
Let me know if the changes in #198 are sufficient to fix this in your opinion. I've added a new field to `UnixAddr`, removed the calls to `strcpy` and `strlen`, and changed the function returning `&Path` to instead return `Option<&Path>`, which bypasses the embedded-NUL check on non-filesystem socket addresses. And added a constructor `new_abstract`, for convenience.

Maybe `.sun_path()` should be public?

**Comment by stouset** [comment]
I'll take a look, thanks!

**Comment by stouset** [comment]
It looks sufficient, but I won't have a chance to play around with it for a bit.
