### ISSUE TITLE
getpeername() panics on AF_UNIX sockets because sockaddr_un varies in size

### ISSUE THREAD

**Issue by geofft** [carllerche/nix-rust#177]
```rust
extern crate nix;
use nix::sys::socket::*;
use nix::unistd::*;

fn main() {
    let (fd1, fd2) = socketpair(AddressFamily::Unix, SockType::Stream, 0, SockFlag::empty()).unwrap();
    getpeername(fd1).unwrap();
}
```
does this:
```
geofft@titan:~/src/rust/scratch/t$ target/debug/t
thread '<main>' panicked at 'assertion failed: len as usize == mem::size_of::<sockaddr_un>()', /home/geofft/src/rust/nix-rust/src/sys/socket/mod.rs:721
```

The panic is in `sockaddr_storage_to_addr`:
```rust
        consts::AF_UNIX => {
            assert!(len as usize == mem::size_of::<sockaddr_un>());
            Ok(SockAddr::Unix(UnixAddr(*(addr as *const _ as *const sockaddr_un))))
        }
```

From some print statements, it looks like `len` is 2, whereas the size of the structure is 110. strace traces this as

```
getpeername(3, {sa_family=AF_LOCAL, NULL}, [2]) = 0
```

It looks like it's valid for a `sockaddr_un` to report a length shorter than the maximum size, and we're supposed to treat this as a flexible array member or something. The easiest answer may be for UnixAddr to explicitly track its own size, although I'm wondering if really SockAddr should track size for all variants.

Probably a prereq for / should be fixed alongside #169.

(Also, `getpeername` has no tests and probably should have at least one.)

**Comment by carllerche** [comment]
Ah... makes sense. And yes, nix definitely could use more tests :)

**Comment by posborne** [comment]
Does anyone have a good idea for mocking out libc calls?  One thought is to use something like `#[link_args = "-Wl,wrap,ioctl]` to wrap system calls, but this is not particularly portable and relies on unstable parts of the language.

This seems to be the biggest barrier to adding better test coverage.

**Comment by geofft** [comment]
I feel like for `getpeername` one ought to be able to use the native OS implementation for all address families, since there's a meaningful localhost. In the general case, is it sufficient to run the tests inside a VM on an isolated network? Then you can test things that involve root (like `mount`), test things that involve all types of network protocols, etc. Some shell scripts to create VMs and run them with qemu should not be too difficult.

For wrapping functions, if you want to take that approach, you could use [my Rust LD_PRELOAD macro library](https://github.com/geofft/redhook). I've been meaning to add Mac support to it via dyld interposers. But I feel like I'd rather see tests pass on actual OSes/kernels
