### ISSUE TITLE
Any plans for new release?

### ISSUE THREAD

**Issue by tailhook** [carllerche/nix-rust#178]
In particular I'm interested in `waitpid` and `clone` functions which were recently fixed. I'm asking because it blocks releasing of my `unshare` crate which deals with linux containers.

**Comment by agrover** [comment]
ioctls appear to be inoperative at the moment.

**Comment by carllerche** [comment]
@agrover what do you mean?

**Comment by agrover** [comment]
@carllerche on further examination I am wrong, I guess `ioctl!` actually is what calls ioctl() now, and no doubt it works :smile:

But some more documentation and examples around ioctl! would be great. I see how iorw!() and friends map to what was in 0.3.9, but converting read_into(x) and read_into_ptr(x) calls into ioctl!(x) is not at all clear to me, or documented as well as the old way was.

(tailhook sorry for hijacking your bug)

**Comment by posborne** [comment]
@agrover, I can work on improving the documentation.  For now, here's a couple pieces of code I have started to put together using the new macros:

* Working: https://github.com/posborne/rust-spidev/compare/nix-ioctl-changes
* WIP: https://github.com/posborne/rust-i2cdev/blob/master/src/linux/ffi.rs#L179 (i2c uses the "bad" ioctl variant; there are rough edges here).

To be honest, I have somewhat mixed feelings about the new macros.  I think they are better in some ways but there will likely need to be some improvement on them over time to get things where they should be long term.  Feedback, changes welcome.

I'm not sure how best to approach other platforms either.  Some research will be required.  I think it would be good to make something like the current "bad" version of the `ioctl!` macro available on all platforms.

**Comment by agrover** [comment]
@posborne thanks that'll get me started!

**Comment by carllerche** [comment]
Done!
