### ISSUE TITLE
ioctl! macro does not allow definition of public ioctl wrappers

### ISSUE THREAD

**Issue by jmesmon** [carllerche/nix-rust#184]
There doesn't seem to be an easy way to simply make public the generated ioctl wrappers without essentially duplicating all of their work (writing wrapping functions with the appropriate signature)

An easy way to prefix with 'pub' would be nice.

**Comment by posborne** [comment]
Ah, sure enough.  I was hoping that it would be possible to just put `pub` in front, but this is clearly not the case.

**Comment by posborne** [comment]
@jmesmon Any thoughts on having pub be what the ioctl supplies.  This is what I have implemented now in my PR.  I'm thinking a common pattern might be to close over `ioctl!` definitions with `mod ioctl` namespace which gives the flexibility to control the visibility.

Other feedback welcome.  If there are warts with the new interface, its probably best to fix them now before too many people have updated their code.

**Comment by jmesmon** [comment]
Well, I looked a bit further at what the current ioctl! macro provides while updating a few of my crates, and I ended up needing some wrapping functions anyhow (bare ioctls rarely make sense).

So despite me opening this issue, I'm not sure I really need a way to make the wrappers pub (that was just the first thing I reached for when updating things).
