### ISSUE TITLE
Linux-only features in nix

### ISSUE THREAD

**Issue by polachok** [carllerche/nix-rust#200]
I just started working on Netlink sockets support for rust.
Do you think adding support for Netlink (only available on linux) is in scope of the project, or it would better to create a separate library reusing parts of Nix?

**Comment by carllerche** [comment]
The exact design guidelines of nix are still in flux (#190). However, nix definitely includes linux only APIs. So, :+1:

**Comment by posborne** [comment]
Netlink supports sounds good to me.  It looks like there is a start to providing libnl bindings for Rust: https://github.com/carrotsrc/rsnl and https://github.com/carrotsrc/rsgnl.  That being said, I would prefer to have a direct syscall interface available.

**Comment by polachok** [comment]
@posborne what do you mean by direct syscall interface? Is [this](https://github.com/polachok/rust-cnproc/blob/master/src/socket.rs) direct enough?

**Comment by posborne** [comment]
Sorry yes.  Syscall was obviously not the right word in this case as netlink uses sockets.  Basically, without wrapping another library like libnl (libc is fine)
