### ISSUE TITLE
ioctl call with nix 0.4.*

### ISSUE THREAD

**Issue by gwenn** [carllerche/nix-rust#201]
Hello,

What it is the equivalent in version 0.4.* to the following call in version 0.3.*:
```rust
ioctl::read_into(libc::STDOUT_FILENO, TIOCGWINSZ, &mut size)
```
(https://github.com/gwenn/rustyline/blob/master/src/lib.rs#L185)

Thanks

**Comment by gwenn** [comment]
Maybe I should use libc directly ?
```rust
libc::ioctl(libc::STDOUT_FILENO, TIOCGWINSZ, &mut size)
```
http://doc.rust-lang.org/libc/x86_64-apple-darwin/libc/fn.ioctl.html

**Comment by posborne** [comment]
This works:

```rust
#![feature(libc)]

#[macro_use]
extern crate nix;
extern crate libc;

use std::mem;
use libc::c_ushort;


#[derive(Debug)]
#[repr(C)]
struct winsize {
    ws_row: c_ushort,
    ws_col: c_ushort,
    ws_xpixel: c_ushort,
    ws_ypixel: c_ushort
}

mod ioctl {
    use libc;

    #[cfg(any(target_os = "macos", target_os = "freebsd"))]
    const TIOCGWINSZ: libc::c_ulong = 0x40087468;
    #[cfg(any(target_os = "linux", target_os = "android"))]
    const TIOCGWINSZ: libc::c_ulong = 0x5413;
    ioctl!(bad read_winsize with TIOCGWINSZ);
}

fn main() {
    unsafe {
        let mut size: winsize = std::mem::zeroed();
        ioctl::read_winsize(0, mem::transmute(&mut size as *mut winsize)).unwrap();
        println!("Size: {:?}", size);
    }
}
```

**Comment by gwenn** [comment]
Thanks.

**Comment by posborne** [comment]
I think the original implementation did probably find the wrong level of abstraction.  Here, it would be nice to use the semantics you get with `read` but that is hard coded to do the equivalent of an `_IOR`.  As discussed in  #190, another option might have been to support both the macro and function interface approach.

For now, I certainly don't want to introduce another set of breaking changes.
