### ISSUE TITLE
Wifi status / signal strength

### ISSUE THREAD

**Issue by franleplant** [carllerche/nix-rust#212]
Hi! 
    Before all, this is **not an issue**, but this might be the best place to ask:

[How] can I check the Wifi signal strength with this library?

Im trying to set up the basis for a little Rust project that informs the user about the Wifi signal strength as diagnostics tool, and so far I've only found Windows API's to get this information, but I'd like this as well from Linux / Unix.

Thanks in advance!
Fran

**Comment by posborne** [comment]
Hi @franleplant.  The low-level interface for getting signal strength on most linux systems will be nl80211 (https://wireless.wiki.kernel.org/en/developers/documentation/nl80211).  This is the interface used by commands such as `iw`:

    $ iw dev wlan2  link
    Connected to 02:40:9d:73:e4:79 (on wlan2)
	SSID: <redacted>
	freq: 2412
	RX: 25417656 bytes (193782 packets)
	TX: 155751 bytes (1835 packets)
	signal: -38 dBm
	tx bitrate: 72.2 MBit/s MCS 7 short GI

	bss flags:	short-preamble short-slot-time
	dtim period:	0
	beacon int:	100

Not *all* devices support the nl80211 interface.  The most portable (but higher level) option on linux might be to parse the output of a command like `iwlist` which is going to be widely available on linux systems.  Alternatively, you might be able to try talking to wpa_supplicant.

Nix does not provide netlink support at this time (nl80211 is built on netlink).  I have not tried it, but you could check out https://github.com/carrotsrc/nl80211rs.

**Comment by posborne** [comment]
Just to follow up.  There is no standard interface to Wi-Fi hardware for things like signal strength on *nix systems.  It is not covered by posix whatsoever.

**Comment by franleplant** [comment]
Thanks a lot @posborne , I know that this thread might take time from your already busy schedule, I appreciate you taking time to answer. ]

The information you provided is really useful, I'll dig more into it, thanks a lot!
Fran
