### ISSUE TITLE
Add safe wrappers for getuid / getgid / geteuid / getegid

### ISSUE THREAD

**Issue by kamalmarhubi** [carllerche/nix-rust#213]
Per [getuid(2)][getuid] and [getgid(2)][getgid], these functions always succeed, so there's not even a wrapper to write.

[getuid]: http://man7.org/linux/man-pages/man2/getuid.2.html#ERRORS
[getgid]: http://man7.org/linux/man-pages/man2/getgid.2.html#ERRORS

**Comment by kamalmarhubi** [comment]
I'm confused because I can't even find the functions now. I'm *sure* I saw them.

**Comment by maghoff** [comment]
FYI, these are already wrapped in another project: https://github.com/ogham/rust-users

**Comment by kamalmarhubi** [comment]
Thanks for that link! Scoped uid changes are nifty. I still think it would be nice to have the basic functions in nix. They are present in libc after all. :-)
