### ISSUE TITLE
Several `const`s should be `bitflags`

### ISSUE THREAD

**Issue by utkarshkukreti** [carllerche/nix-rust#58]
Some random examples (there are many more):

* [MmapFlag](https://github.com/carllerche/nix-rust/blob/9a17a4d200b33f66a6d61dc06a9df7ddef01d735/src/sys/mman.rs#L13-L32)
* [MmapProt](https://github.com/carllerche/nix-rust/blob/9a17a4d200b33f66a6d61dc06a9df7ddef01d735/src/sys/mman.rs#L34-L41)
* [SockMessageFlags](https://github.com/carllerche/nix-rust/blob/9a17a4d200b33f66a6d61dc06a9df7ddef01d735/src/sys/socket.rs#L221-L225)

**Comment by carllerche** [comment]
Looks like you are correct :)

**Comment by fiveop** [comment]
After #243 only flags in `src/sys/socket/consts.rs` should remain to be converted.

**Comment by kamalmarhubi** [comment]
@fiveop are you working on the remaining flags?

**Comment by fiveop** [comment]
I think we can close this now.

**Comment by kamalmarhubi** [comment]
@fiveop did you convert the ones in the original issue, or go over all flags? If the former, I think we could keep this open pending an audit to make sure we're using bitflags all over.

**Comment by fiveop** [comment]
I am pretty sure that I found all of them, but please do check again.

**Comment by kamalmarhubi** [comment]
@fiveop skimmed all the source, looks good!
