### ISSUE TITLE
interested in mq support (Posix message queues)?

### ISSUE THREAD

**Issue by MarkusJais** [carllerche/nix-rust#62]
Hi,

I am  interested in providing Rust bindings to the Posix message queues. 

Would this be something for nix-rust?

I would love to add this.

Markus

**Comment by carllerche** [comment]
Sure!

**Comment by MarkusJais** [comment]
Cool. Already started working on it.

**Comment by MarkusJais** [comment]
I am making progress here after the compiler and I resolved our misunderstandings :-)
I hope to have a basic version soon.

**Comment by MarkusJais** [comment]
I've finally got a basic working version. It does not yet support all functions but basic sending/received is working.
It would be nice if somebody could have a look before I create a pull request. All feedback is welcome.

https://github.com/MarkusJais/nix-rust/commit/3a09f4e7b638ce279b9d0769062a991a72518deb

**Comment by MarkusJais** [comment]
I close this one as I am working on it. It might currently be broken but I'll open a new one for that.
