### ISSUE TITLE
Rename project to avoid confusion with Nix.

### ISSUE THREAD

**Issue by eddyb** [carllerche/nix-rust#76]
While I don't mind "\*nix" to denote Unix (and Unix-like) systems, "Nix" specifically is taken by [the "purely functional package manager"](http://nixos.org/nix/).
This could get worse in the future, because of how cargo fits *almost perfectly* with the Nix model, and I have seen integration prototypes already.
You might have to deal with `crates.io` packages that interact with Nix, or even fully reimplement it in Rust.

I know it doesn't sound as cool, but what about "posix.rs" or some variation thereof?

**Comment by rrichardson** [comment]
How about we move its contents to the libc crate?

**Comment by carllerche** [comment]
libc is mostly just FFI bindings and const declarations. nix is trying to provide somewhat of a rusty api.

`posix.rs` isn't ideal because the library provides far more than than just `posix` APIs. It tries to cover all of the *nix OSes (hence the name). I would be open to switching the name if somebody proposes a good one, but while I am sympathetic w/ library name clashes, "nix" is a very very generic name w/ plenty of history prior to the package manager.

Anyway, like I said, i am open to name proposals.

**Comment by utkarshkukreti** [comment]
Also, a project named posix.rs [already exists](https://github.com/mahkoh/posix.rs).

**Comment by little-arhat** [comment]
OCaml has `Unix` module, that provides interface to common unix facilities. http://caml.inria.fr/pub/docs/manual-ocaml/libref/Unix.html . `unix.rs` may be good choice: it retains `nix` part and avoids confusion with `Nix`.

**Comment by tbu-** [comment]
This probably needs a decision before 1.0. My suggestion: Either close this issue and leave the name, or rename the project. Just ignoring the issue doesn't make it go away. :/

**Comment by carllerche** [comment]
I agree this needs to be decided before 1.0

As I see it, there are two main arguments for keeping the name `nix`:

1) Historically, "*nix" has been "a shorthand form referring to Unix-like computer operating systems". This predates the nix package manager. If there was a collision on a unique word / name given the space, I would think the argument to rename this library would be stronger.

2) `nix` is a core part of the API. It is useful to have a short, meaningful, 3 letter prefix to these apis as they come up a lot when using the library: `nix::Error`, `nix::Result`, `nix::fcntl(...)`, etc... Yes it would be possible for people to do: `extern crate someothername as nix;` but using `nix seems like a good default.

I will try to get a wider set of opinions before making a final decision.

**Comment by cmr** [comment]
This is an unfortunate collision. `nix` is *such* a nice name. At the same time, `unix` isn't a bad name.

**Comment by brson** [comment]
That's a tough call. I'm inclined to keep the name 'nix'. It's potentially confusing, but it's cute and historical precedent is on unix's side. More people know unix than 'nix the package manager'.

**Comment by lambda** [comment]
I don't think that `nix` is too confusing, and I don't know if it's likely that there would ever need to be a crate for the package manager (and if so, it could be called `nix-pkg` or something like that). However, I'm not a user or developer of nix/NixOS, I don't know if they would feel differently.

If it is changed, I agree that `posix` isn't a great name, as there are many APIs that apply to Unix like systems that aren't standardized (xattrs, epoll/kqueue, etc), and would be good to have Rusty wrappers around.

I don't think that `unix` would be very good either, as it might be confused with `std::os::unix`.

I might suggest `nixie` as an alternative name, if you do decide to change the name. Still has the reference to *nix, reasonably short, not limited to standardized APIs nor confusable with any part of the standard library.

**Comment by tbu-** [comment]
I like `nixie`, it's one of the "creative package names" crates.io strives for with its flat namespace.

**Comment by wycats** [comment]
@tbu- the problem doesn't seem to be a namespacing issue -- `carllerche/nix` would have the same problem.

**Comment by rrichardson** [comment]
I think before we have this discussion we should ask the Nix Linux people
if they'll kindly change their name to something less ambiguous.

I am partial to Hipster Linux.

**Comment by wycats** [comment]
The thing that's surprising to me about this discussion is that it seems like the nix package manager is the one that stomped on the namespace... and then somehow succeeded in owning it!

The name "*nix" to refer to the family of Unix operating system is very, very old. I'm honestly kind of at a loss for how the package manager managed to not only use this already-precedented name, but now make it seem like using it in the traditional way is conflicting with it!

**Comment by tbu-** [comment]
@wycats Sorry for my snarky remark.

To me it's kind of irrelevant who was there first, but rather that there might be confusion about the name. Carrying out a discussion about "who was there first" doesn't mitigate the problems though.

**Comment by dwrensha** [comment]
I like the name "unix" for this crate. To me, "*nix" means "unix-like" but "nix" unambiguously refers to the package manager.

**Comment by redrampage** [comment]
Hello, sorry for barging in, but IMHO "unix" would be a better name for this lib, it's short and self-explanatory.
"nix" without an asterisk doesn't resemble "*nix" very well.
"nixie" is too long for such a "core" library and pretty much refers to "nixie tubes".

**Comment by carllerche** [comment]
I attempted to contact the nix package manager author, but did not hear back. I have not been convinced that a rename is worth it given the history of "nix" meaning *nix / unix flavored.

I am going to keep the nix name.

**Comment by domenkozar** [comment]
We also have rust integration for Nix(OS), so this will yield some really bad UX in the future :)

https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/rust-packages.nix

**Comment by shadowcat-mst** [comment]
@carllerche the nix package manager has been going a long time - quite possibly longer than rust has existed - so expecting them to rename at this point seems a little silly.

How about renaming this package to 'starnix' ?

**Comment by nox** [comment]
@carllerche I'm not sure what your intent was by trying to contact the Nix package manager author… Did you want to ask them to rename their project? This crate being called Nix is highly confusing.

**Comment by nox** [comment]
What about kleenix, playing both on the Kleene star and the fact that such abstractions make us cry less? (Kleenex as in tissue)

**Comment by nathan7** [comment]
If anyone is in the possession of a time machine to the year 2003, we might be able to get Nix, nixpkgs, and NixOS renamed. But I'm afraid I don't have one of those laying around.

**Comment by shadowcat-mst** [comment]
@wycats basically from my point of view it's "don't confuse the sysadmin", and nix is a well established name at this point among people who've been paying attention to 'doing systems level stuff better'. I'm not claiming their choice of name is perfect, but that ship sailed ten years ago whereas we can avoid causing problems here, now.

**Comment by crertel** [comment]
I'd like to humbly second the vote for "starnix".

**Comment by posborne** [comment]
@nbp 
> I agree with @domenkozar , not renaming will cause a name clash in various package managers, not only Nixpkgs.

I fail to see how the name will cause conflicts in package management systems but am willing to listen if there is an angle I am missing.  To my knowledge, distros are very good at prefixing library code with the name of the language (e.g. [python-*](https://packages.debian.org/search?keywords=python-&searchon=names&suite=jessie&section=all) in debian).  Is this not the case for nixos?

The existing release for "nix" on crates.io will never be removed (that could and would break existing code).  I suggest that rust packages related to nixos adopt the "nixos" name.  As is, I do not see packages written for dealing with nixos that share this prefix: https://crates.io/search?q=nix

**Comment by shadowcat-mst** [comment]
On Sat, Apr 16, 2016 at 05:40:30PM -0700, Paul Osborne wrote:
> The existing release for "nix" on crates.io will never be removed (that could and would break existing code).  I suggest that rust packages related to nixos adopt the "nixos" name.  As is, I do not see packages written for dealing with nixos that share this prefix: https://crates.io/search?q=nix

I suggest that the answer is both. Or, more precisely -

1) nix renames itself to something less confusing

2) do a final release of nix on crates.io explaining the fuckup and the new name

3) NixOS related packages use nixos, nix-the-package-manager packages use
nixpkg or similar for their name.

(the 'nix' package manager is absolutely usable outside of, and predates,
nixos by some time, trying to file all related things under 'nixos' is an
error, albeit an easy one to make given not already understanding the topic)

-- 
Matt S Trout - Shadowcat Systems - Perl consulting with a commit bit and a clue

http://shadowcat.co.uk/blog/matt-s-trout/   http://twitter.com/shadowcat_mst/

Email me now on mst (at) shadowcat.co.uk and let's chat about how our CPAN
commercial support, training and consultancy packages could help your team.

**Comment by nox** [comment]
[Packages have already been renamed in the past, it's nothing new.](https://github.com/diwic/dbus-rs/issues/9)

**Comment by rrichardson** [comment]
How about posix-rs? Or rust-posix?  Soon Windows will have POSIX support,
so it's not just *nixes :). Yes the support of the current nix is broader
than POSIX, but it gets the point across that it is a wrapper around UNIX
system functions.

**Comment by tbu-** [comment]
https://crates.io/crates/posix is already taken.

**Comment by rrichardson** [comment]
It hasn't been updated in a year.  It looks like its author has moved on to
other things. We could probably acquire rights to the crate name :)
