### ISSUE TITLE
bind sendmsg/recvmsg for Unix socket control messages/ancillary data

### ISSUE THREAD

**Issue by swinbio** [carllerche/nix-rust#88]
Right now nix exposes bindings to sendto/recvfrom which work for the data part of Unix socket messages, but which cannot interact with control messages such as file descriptors sent over Unix sockets. The library should also bind these as they're one of the distinguishing features of Unix sockets.

**Comment by carllerche** [comment]
Hey, this is definitely something that I would like to add, but I am a bit swamped right now w/ work. I would accept a PR that adds this feature though.

**Comment by geofft** [comment]
I have a patchset for this that's almost done; I'll send a PR in a day or two.
