### ISSUE TITLE
`sigaction` should probably be `unsafe`

### ISSUE THREAD

**Issue by tbu-** [carllerche/nix-rust#90]
If you access thread-local data in a signal handler or panic, you probably invoke UB.

http://users.rust-lang.org/t/unix-signals-in-rust/733/3

**Comment by carllerche** [comment]
Pinging @wycats

**Comment by l0kod** [comment]
cc [Safe async/reentrant closure](http://internals.rust-lang.org/t/safe-async-reentrant-closure-e-g-signal-handler/1742)

**Comment by tbu-** [comment]
Meh. It's relatively easy to mark the function unsafe. Should I make a pull request?
