### ISSUE TITLE
cpuset_attribs not defined for ARM Linux

### ISSUE THREAD

**Issue by posborne** [carllerche/nix-rust#95]
No cpuset_attributes are defined for arch "arm" and os "linux".  This results in compilation errors when cross-compiling for triples like "arm-unknown-linux-gnueabihf" used by boards like the raspberry pi and beaglebone black.

I  copied the cpuset_attribs from android and these worked for my use case.

```
   Compiling nix v0.3.3
.../nix-0.3.3/src/sched.rs:94:25: 94:52 error: failed to resolve. Use of undeclared type or module `cpuset_attribs`
.../nix-0.3.3/src/sched.rs:94     cpu_mask: [CpuMask; cpuset_attribs::CPU_SETSIZE/cpuset_attribs::CPU_MASK_BITS]
```

**Comment by carllerche** [comment]
There isn't that great ARM support right now, mostly because it isn't hooked into CI. If you have a PR adding `cpuset_attribs` for ARM linux, I will pull it in. In the mean time, I opened up an issue for improving ARM support: #97.
