### ISSUE TITLE
What happened with eventfd?

### ISSUE THREAD

**Issue by diwic** [carllerche/nix-rust#96]
I used eventfds as a building block (for benchmarks in my fdringbuf crate), and found that it was suddenly gone (to make it compile on the beta, according to a recent commit).

I'm not really sure what the problem is and if it's easy to bring it back, both on the nightly and on the beta...?

**Comment by carllerche** [comment]
Sorry about that, I was using `#[linkage = weak]` as a strategy for providing features that were not globally available. This strategy does not work anymore on beta and will not be stabilized anytime in the foreseeable future. I have plans to bring it back, but it will require a bunch of work.

I can either bring it back via a feature flag until I have time to implement the correct strategy, or you could run a fork that has it. Which would you prefer?

**Comment by carllerche** [comment]
Here, I pushed it back behind a feature flag: 9b0a534962f3a2852491a3b0bc4d4e857f2a1382

My plan is to move the feature detection to a build script vs. providing each feature via a feature flag.

**Comment by carllerche** [comment]
Closing for now, feel free to open another issue if this doesn't resolve your problem.

**Comment by diwic** [comment]
Just dropping by to say thanks for the super-quick fix! I can confirm that it works as expected and I can now again run "cargo bench" for my fdringbuf crate.
